// <auto-generated />
using System;
using MangaScans.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaScans.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240916184922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MangaScans.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6657),
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6658),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6658),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6659),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6660),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6660),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6661),
                            Name = "Suspense"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6661),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6662),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6663),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6663),
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6664),
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6665),
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6665),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6666),
                            Name = "Harem"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6667),
                            Name = "Yaoi"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6667),
                            Name = "Yuri"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 9, 16, 18, 49, 21, 313, DateTimeKind.Utc).AddTicks(6668),
                            Name = "Isekai"
                        });
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdManga")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Num")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdManga");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdChapter")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdChapter");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Manga", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("MangaScans.Domain.Entities.Manga", "_Manga")
                        .WithMany("_Chapters")
                        .HasForeignKey("IdManga")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("_Manga");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Images", b =>
                {
                    b.HasOne("MangaScans.Domain.Entities.Chapter", "_Chapter")
                        .WithMany("_Images")
                        .HasForeignKey("IdChapter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Chapter");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Manga", b =>
                {
                    b.HasOne("MangaScans.Domain.Entities.Category", "_Categories")
                        .WithMany("Mangas")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Categories");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Category", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("_Images");
                });

            modelBuilder.Entity("MangaScans.Domain.Entities.Manga", b =>
                {
                    b.Navigation("_Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
